FROM node:18.13-alpine

# Create a working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Set environment variables
ENV NODE_ENV=devlopment
ENV PORT=5000

# Expose port 5000
EXPOSE 5000

# Start the server
CMD ["npm", "start"]